name: iframe-tester
services:
  appserver:
    ssl: true
    sslExpose: false
    type: node:18
    command: node server.js
proxy:
  appserver:
    - domain1.com
    - domain2.com
    - domain3.com
    - domain4.com
    - domain5.com
    - domain6.com
